
DROP TABLE IF EXISTS rag.inheritance;
DROP TABLE IF EXISTS rag.structure;
DROP TABLE IF EXISTS rag.cooperation;
DROP TABLE IF EXISTS rag.klazz;


CREATE TABLE IF NOT EXISTS rag.klazz
(
    id_auto bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_uid character varying(32) COLLATE pg_catalog."default" NOT NULL,
    touch_uid character varying(32) COLLATE pg_catalog."default",
    is_jdk integer NOT NULL DEFAULT 0,
    jar_simple_name character varying(2048) COLLATE pg_catalog."default" NOT NULL,
    pckg character varying(2048) COLLATE pg_catalog."default" NOT NULL,
    typex character varying(256) COLLATE pg_catalog."default" NOT NULL,
    simple_name character varying(2048) COLLATE pg_catalog."default" NOT NULL,
    full_canonical_name character varying(2048) COLLATE pg_catalog."default" NOT NULL,
    full_type_name character varying(2048) COLLATE pg_catalog."default" NOT NULL,
    sub_level integer NOT NULL DEFAULT 0,
    src_code text COLLATE pg_catalog."default",
    CONSTRAINT klazz_pkey PRIMARY KEY (id_uid),
    CONSTRAINT klazz_id_auto UNIQUE (id_auto)
);

CREATE UNIQUE INDEX IF NOT EXISTS klazz_idx_jar_full_canonical
    ON rag.klazz (jar_simple_name, full_canonical_name);

CREATE INDEX IF NOT EXISTS klazz_idx_full_canonical
    ON rag.klazz (full_canonical_name);


CREATE TABLE IF NOT EXISTS rag.inheritance
(
    id_auto bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_uid character varying(32) COLLATE pg_catalog."default" NOT NULL,
    touch_uid character varying(32) COLLATE pg_catalog."default",
    rel_type character varying(32) COLLATE pg_catalog."default" NOT NULL,
    id_from character varying(32) COLLATE pg_catalog."default" NOT NULL,
    simple_name_from character varying(2048) COLLATE pg_catalog."default" NOT NULL,
    id_to character varying(32) COLLATE pg_catalog."default" NOT NULL,
    simple_name_to character varying(2048) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT inheritance_pkey PRIMARY KEY (id_uid),
    CONSTRAINT inheritance_id_auto UNIQUE (id_auto),
    CONSTRAINT inheritance_fk_id_from
        FOREIGN KEY (id_from)
            REFERENCES rag.klazz(id_uid)
            ON DELETE CASCADE,
    CONSTRAINT inheritance_fk_id_to
        FOREIGN KEY (id_to)
            REFERENCES rag.klazz(id_uid)
            ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS inheritance_idx_id_from
    ON rag.inheritance (id_from);


CREATE TABLE IF NOT EXISTS rag.structure
(
    id_auto bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_uid character varying(32) COLLATE pg_catalog."default" NOT NULL,
    id_klazz character varying(32) COLLATE pg_catalog."default" NOT NULL,
    klazz_simple_name character varying(2048) COLLATE pg_catalog."default" NOT NULL,
    id_klazz_field character varying(32) COLLATE pg_catalog."default" NOT NULL,
    klazz_field_simple_name character varying(2048) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT structure_pkey PRIMARY KEY (id_uid),
    CONSTRAINT structure_id_auto UNIQUE (id_auto),
    CONSTRAINT structure_fk_id_klazz
        FOREIGN KEY (id_klazz)
            REFERENCES rag.klazz(id_uid)
            ON DELETE CASCADE,
    CONSTRAINT structure_fk_id_klazz_field
        FOREIGN KEY (id_klazz_field)
            REFERENCES rag.klazz(id_uid)
            ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS structure_idx_id_klazz
    ON rag.structure (id_klazz);


CREATE TABLE IF NOT EXISTS rag.cooperation
(
    id_auto bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_uid character varying(32) COLLATE pg_catalog."default" NOT NULL,
    id_klazz character varying(32) COLLATE pg_catalog."default" NOT NULL,
    klazz_simple_name character varying(2048) COLLATE pg_catalog."default" NOT NULL,
    id_klazz_of_parameter character varying(32) COLLATE pg_catalog."default" NOT NULL,
    klazz_of_parameter_simple_name character varying(2048) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cooperation_pkey PRIMARY KEY (id_uid),
    CONSTRAINT cooperation_id_auto UNIQUE (id_auto),
    CONSTRAINT cooperation_fk_id_klazz
        FOREIGN KEY (id_klazz)
            REFERENCES rag.klazz(id_uid)
            ON DELETE CASCADE,
    CONSTRAINT cooperation_fk_id_klazz_of_parameter
        FOREIGN KEY (id_klazz_of_parameter)
            REFERENCES rag.klazz(id_uid)
            ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS cooperation_idx_id_klazz
    ON rag.cooperation (id_klazz);
