

###
http://localhost:8886/ragdeterm?query=
    For the following set of types in Java
    ```java
    [*RG StructureContext("pl.org.opi.vehicle.land.car.subtypes.Hatchback",
    "", SOURCE_CODE, "\n", "\n", "\n") *RG]
    ```java
    create their equivalents in Typescript.
