spring.application.name=ai-client-naive
server.port=8883
spring.ai.openai.chat.options.temperature=0.1

## spring.ai.openai.chat.options.model=gpt-3.5-turbo
## spring.ai.openai.chat.options.model=gpt-4o-2024-11-20
spring.ai.openai.chat.options.model=gpt-4o-mini-2024-07-18
## spring.ai.openai.chat.options.model=gpt-5-mini-2025-08-07

##spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.ai.openai.embedding.options.model=text-embedding-3-large

create.store=false
## vector.file.name=vector-db-embedding-3-small.json
vector.file.name=vector-db-embedding-3-large.json

source.folder.1=c:/ragdeterm/hierarchy-lib/src/main/java
source.folder.2=c:/ragdeterm/vehicle-lib/src/main/java
source.folder.3=c:/ragdeterm/person-lib/src/main/java
source.folder.4=c:/ragdeterm/depend-a-lib/src/main/java
source.folder.5=c:/ragdeterm/depend-b-lib/src/main/java
source.folder.6=c:/ragdeterm/depend-c-lib/src/main/java

