@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "pl.org.opi.common.AcademicDegree",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_110308 { 
   	label=org
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1205980002 { 
   	label=opi
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Academic1136857303[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Academic</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   academicDegree: AcademicDegree [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># canEqual(other: Object): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

AcademicDegree773758829[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(E)AcademicDegree</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   BACHELOR: AcademicDegree [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   DOCTOR: AcademicDegree [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   HABILITATION: AcademicDegree [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   MASTER: AcademicDegree [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   NONE: AcademicDegree [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   PROFESSOR: AcademicDegree [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ valueOf(name: String): AcademicDegree</TD></TR>
<TR><TD ALIGN="LEFT" >+ values(): AcademicDegree[]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#DCFBD5"
];

PersonSection1136857303[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PersonSection</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   academic: Academic [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   documentId: BigInteger [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   personalData: PersonalData [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   sectionId: BigInteger [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># canEqual(other: Object): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
Academic1136857303 -> AcademicDegree773758829[label="academicDegree
[0..1]"];
PersonSection1136857303 -> Academic1136857303[label="academic
[0..1]"];
    
}
@enduml